<?php
/**
* @file
* Módulo de ejemplo
* Este módulo presenta un mensaje de bienvenida al usuario en un bloque.
*/

/**
 * Implements hook_block_info().
 */
function first_example_block_info() {
  // This example comes from node.module.
  $blocks['welcome'] = array(
    'info' => t('My first module: welcome block'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function first_example_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'welcome':
      $block['subject'] = t('My first module');
      $block['content'] = t(variable_get('first_example_message'));
      break;
  }
  return $block;
}

/**
 * Implements hook_help().
 */
function first_example_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    case 'admin/help#first_example':
      return '<p>' . t('This module shows a welcome message into a 
              block.') . '</p>';
    case 'admin/structure/block':
      return '<p>' . t('Use the block Welcome block to show a 
              welcome message.') . '</p>';
    case 'user/%':
      if ($arg[1] == 1) {
        return '<p>' . t('Activating the module First example, the users
               of the site will receive a message of welcome') . '</p>';
      }
  }
}

/**
 * Implements hook_menu().
 */
function first_example_menu() {
  $items['admin/config/workflow/first_example'] = array(
    'title' => 'First example settings',
    'description' => 'Settings for module First Example',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('first_example_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'first_example.admin.inc',
  );
return $items;
}