<?php
/**
* @file
* Módulo de ejemplo
* Este módulo presenta un mensaje de bienvenida al usuario en un bloque.
*/

/**
 * Implements hook_block_info().
 */
function first_example_block_info() {
  // This example comes from node.module.
  $blocks['welcome'] = array(
    'info' => t('My first module: welcome block'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function first_example_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'welcome':
      $block['subject'] = t('My first module');
      $block['content'] = t('Welcome to my Drupal site.');
      break;
  }
  return $block;
}

/**
 * Implements hook_help().
 */
function first_example_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    case 'admin/help#first_example':
      return '<p>' . t('This module shows a welcome message into a 
              block.') . '</p>';
    case 'admin/structure/block':
      return '<p>' . t('Use the block Welcome block to show a 
              welcome message.') . '</p>';
    case 'user/%':
      if ($arg[1]==1){
        return '<p>' . t('Activating the module First example, the users
               of the site will receive a message of welcome') . '</p>';
      }
  }
}